# Generated by Django 4.0.4 on 2022-05-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPcte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crio_pte',
            old_name='estario_C',
            new_name='estadio_C',
        ),
    ]
